[build]
  command = "cd frontend && npm install && npm run build"
  functions = "functions"
  publish = "frontend/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["serverless-http"]

[build.environment]
  NODE_VERSION = "18"

