[build]
  command = "cd frontend && npm install && npm run build"
  functions = "functions"
  publish = "frontend/dist"

[[redirects]]
  from = "/.netlify/functions/server/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["serverless-http", "mongoose", "express"]
  included_files = ["functions/**/*"]

[build.environment]
  NODE_VERSION = "18"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "frontend/dist"

